"""initial_schema

Revision ID: 99747162cf82
Revises:
Create Date: 2026-04-04 18:51:11.936686
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "99747162cf82"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_name", sa.String(length=255), nullable=False),
        sa.Column("institution_type", sa.String(length=30), nullable=False),
        sa.Column("subscription_plan", sa.String(length=20), nullable=False),
        sa.Column("plan_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("plan_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("db_type", sa.String(length=30), nullable=True),
        sa.Column("db_url_encrypted", sa.Text(), nullable=True),
        sa.Column("db_config_json", sa.JSON(), nullable=True),
        sa.Column("model_strategy", sa.String(length=20), nullable=False),
        sa.Column("active_model_id", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=30), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("address_line_1", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state_province", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("account_opening_date", sa.Date(), nullable=True),
        sa.Column("account_status", sa.String(length=20), nullable=False),
        sa.Column("kyc_status", sa.String(length=20), nullable=False),
        sa.Column("kyc_verification_level", sa.String(length=20), nullable=False),
        sa.Column("risk_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("customer_tier", sa.String(length=20), nullable=False),
        sa.Column("balance_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("active_card_count", sa.Integer(), nullable=False),
        sa.Column("preferred_card_token", sa.String(length=255), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=False)
    op.create_index(op.f("ix_customers_tenant_id"), "customers", ["tenant_id"], unique=False)
    op.create_table(
        "fraud_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("rule_name", sa.String(length=255), nullable=False),
        sa.Column("rule_category", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("notify_channels", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("false_positive_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("hit_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("total_triggers", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fraud_rules_is_active"), "fraud_rules", ["is_active"], unique=False)
    op.create_index(op.f("ix_fraud_rules_tenant_id"), "fraud_rules", ["tenant_id"], unique=False)
    op.create_table(
        "ml_models",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_type", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("precision", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("recall", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("f1_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("auc_roc", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("false_positive_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("training_samples", sa.Integer(), nullable=True),
        sa.Column("artifact_path", sa.String(length=500), nullable=True),
        sa.Column("feature_importance", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ml_models_tenant_id"), "ml_models", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=30), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supabase_uid", sa.String(length=255), nullable=True),
        sa.Column("has_completed_onboarding", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supabase_uid"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=True),
        sa.Column("card_id", sa.String(length=255), nullable=True),
        sa.Column("merchant_id", sa.String(length=255), nullable=True),
        sa.Column("merchant_name", sa.String(length=255), nullable=True),
        sa.Column("merchant_category_code", sa.String(length=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("location_lat", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("location_lng", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("fraud_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("fraud_risk_level", sa.String(length=10), nullable=True),
        sa.Column("fraud_category", sa.String(length=20), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("triggered_rule_ids", app.models.transaction.SafeJSON(), nullable=True),  # noqa: F821
        sa.Column("shap_values", sa.JSON(), nullable=True),
        sa.Column("fraud_scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transaction_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_customer_id"), "transactions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_fraud_category"), "transactions", ["fraud_category"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_fraud_score"), "transactions", ["fraud_score"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_is_flagged"), "transactions", ["is_flagged"], unique=False
    )
    op.create_index(op.f("ix_transactions_is_test"), "transactions", ["is_test"], unique=False)
    op.create_index(op.f("ix_transactions_tenant_id"), "transactions", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_transactions_transaction_timestamp"),
        "transactions",
        ["transaction_timestamp"],
        unique=False,
    )
    op.create_table(
        "fraud_alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("customer_id", sa.String(length=36), nullable=True),
        sa.Column("alert_type", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("analyst_id", sa.String(length=36), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("notifications_sent", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["analyst_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fraud_alerts_created_at"), "fraud_alerts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_fraud_alerts_customer_id"), "fraud_alerts", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_fraud_alerts_severity"), "fraud_alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_fraud_alerts_status"), "fraud_alerts", ["status"], unique=False)
    op.create_index(op.f("ix_fraud_alerts_tenant_id"), "fraud_alerts", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_fraud_alerts_transaction_id"), "fraud_alerts", ["transaction_id"], unique=False
    )
    op.create_table(
        "investigation_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("alert_id", sa.String(length=36), nullable=True),
        sa.Column("customer_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_to", sa.String(length=36), nullable=True),
        sa.Column("case_number", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=True),
        sa.Column("notes", sa.JSON(), nullable=True),
        sa.Column("linked_transaction_ids", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["fraud_alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_number"),
    )
    op.create_index(
        op.f("ix_investigation_cases_tenant_id"), "investigation_cases", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_investigation_cases_tenant_id"), table_name="investigation_cases")
    op.drop_table("investigation_cases")
    op.drop_index(op.f("ix_fraud_alerts_transaction_id"), table_name="fraud_alerts")
    op.drop_index(op.f("ix_fraud_alerts_tenant_id"), table_name="fraud_alerts")
    op.drop_index(op.f("ix_fraud_alerts_status"), table_name="fraud_alerts")
    op.drop_index(op.f("ix_fraud_alerts_severity"), table_name="fraud_alerts")
    op.drop_index(op.f("ix_fraud_alerts_customer_id"), table_name="fraud_alerts")
    op.drop_index(op.f("ix_fraud_alerts_created_at"), table_name="fraud_alerts")
    op.drop_table("fraud_alerts")
    op.drop_index(op.f("ix_transactions_transaction_timestamp"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_tenant_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_is_test"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_is_flagged"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_fraud_score"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_fraud_category"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_customer_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ml_models_tenant_id"), table_name="ml_models")
    op.drop_table("ml_models")
    op.drop_index(op.f("ix_fraud_rules_tenant_id"), table_name="fraud_rules")
    op.drop_index(op.f("ix_fraud_rules_is_active"), table_name="fraud_rules")
    op.drop_table("fraud_rules")
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_table("customers")
    op.drop_table("tenants")
    # ### end Alembic commands ###
